apiVersion: carto.run/v1alpha1
kind: Workload
metadata:  
  labels:
    app.kubernetes.io/part-of: jon-java-web-app-gary
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
  name: jon-java-web-app-gary
  namespace: gary  
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/JonathanOram/tanzu-java-web-app
      